"""
sp500.py - S&P 500 constituents (GICS sector / sub-industry), Dow 30, and Arabic names of GICS sub-industries.
Source: github.com/datasets/s-and-p-500-companies (Sep 2026). Sectors are mapped to the Yahoo names used across the site.
"""
from i18n import L

# symbol -> (company, sector, GICS sub-industry)
SP500 = {
    "A": ('Agilent Technologies', "Healthcare", 'Life Sciences Tools & Services'),
    "AAPL": ('Apple Inc.', "Technology", 'Technology Hardware, Storage & Peripherals'),
    "ABBV": ('AbbVie', "Healthcare", 'Biotechnology'),
    "ABNB": ('Airbnb', "Consumer Cyclical", 'Hotels, Resorts & Cruise Lines'),
    "ABT": ('Abbott Laboratories', "Healthcare", 'Health Care Equipment'),
    "ACGL": ('Arch Capital Group', "Financial Services", 'Property & Casualty Insurance'),
    "ACN": ('Accenture', "Technology", 'IT Consulting & Other Services'),
    "ADBE": ('Adobe Inc.', "Technology", 'Application Software'),
    "ADI": ('Analog Devices', "Technology", 'Semiconductors'),
    "ADM": ('Archer Daniels Midland', "Consumer Defensive", 'Agricultural Products & Services'),
    "ADP": ('Automatic Data Processing', "Industrials", 'Human Resource & Employment Services'),
    "ADSK": ('Autodesk', "Technology", 'Application Software'),
    "AEE": ('Ameren', "Utilities", 'Multi-Utilities'),
    "AEP": ('American Electric Power', "Utilities", 'Electric Utilities'),
    "AES": ('AES Corporation', "Utilities", 'Independent Power Producers & Energy Traders'),
    "AFL": ('Aflac', "Financial Services", 'Life & Health Insurance'),
    "AIG": ('American International Group', "Financial Services", 'Multi-line Insurance'),
    "AIZ": ('Assurant', "Financial Services", 'Multi-line Insurance'),
    "AJG": ('Arthur J. Gallagher & Co.', "Financial Services", 'Insurance Brokers'),
    "AKAM": ('Akamai Technologies', "Technology", 'Internet Services & Infrastructure'),
    "ALB": ('Albemarle Corporation', "Basic Materials", 'Specialty Chemicals'),
    "ALGN": ('Align Technology', "Healthcare", 'Health Care Supplies'),
    "ALL": ('Allstate', "Financial Services", 'Property & Casualty Insurance'),
    "ALLE": ('Allegion', "Industrials", 'Building Products'),
    "AMAT": ('Applied Materials', "Technology", 'Semiconductor Materials & Equipment'),
    "AMCR": ('Amcor', "Basic Materials", 'Paper & Plastic Packaging Products & Materials'),
    "AMD": ('Advanced Micro Devices', "Technology", 'Semiconductors'),
    "AME": ('Ametek', "Industrials", 'Electrical Components & Equipment'),
    "AMGN": ('Amgen', "Healthcare", 'Biotechnology'),
    "AMP": ('Ameriprise Financial', "Financial Services", 'Asset Management & Custody Banks'),
    "AMT": ('American Tower', "Real Estate", 'Telecom Tower REITs'),
    "AMZN": ('Amazon', "Consumer Cyclical", 'Broadline Retail'),
    "ANET": ('Arista Networks', "Technology", 'Communications Equipment'),
    "AON": ('Aon plc', "Financial Services", 'Insurance Brokers'),
    "AOS": ('A. O. Smith', "Industrials", 'Building Products'),
    "APA": ('APA Corporation', "Energy", 'Oil & Gas Exploration & Production'),
    "APD": ('Air Products', "Basic Materials", 'Industrial Gases'),
    "APH": ('Amphenol', "Technology", 'Electronic Components'),
    "APO": ('Apollo Global Management', "Financial Services", 'Asset Management & Custody Banks'),
    "APP": ('AppLovin', "Communication Services", 'Advertising'),
    "APTV": ('Aptiv', "Consumer Cyclical", 'Automotive Parts & Equipment'),
    "ARE": ('Alexandria Real Estate Equities', "Real Estate", 'Office REITs'),
    "ARES": ('Ares Management', "Financial Services", 'Asset Management & Custody Banks'),
    "ATO": ('Atmos Energy', "Utilities", 'Gas Utilities'),
    "AVGO": ('Broadcom', "Technology", 'Semiconductors'),
    "AVY": ('Avery Dennison', "Basic Materials", 'Paper & Plastic Packaging Products & Materials'),
    "AWK": ('American Water Works', "Utilities", 'Water Utilities'),
    "AXON": ('Axon Enterprise', "Industrials", 'Aerospace & Defense'),
    "AXP": ('American Express', "Financial Services", 'Consumer Finance'),
    "AZO": ('AutoZone', "Consumer Cyclical", 'Automotive Retail'),
    "BA": ('Boeing', "Industrials", 'Aerospace & Defense'),
    "BAC": ('Bank of America', "Financial Services", 'Diversified Banks'),
    "BALL": ('Ball Corporation', "Basic Materials", 'Metal, Glass & Plastic Containers'),
    "BAX": ('Baxter International', "Healthcare", 'Health Care Equipment'),
    "BBY": ('Best Buy', "Consumer Cyclical", 'Computer & Electronics Retail'),
    "BDX": ('Becton Dickinson', "Healthcare", 'Health Care Equipment'),
    "BE": ('Bloom Energy', "Industrials", 'Electrical Components & Equipment'),
    "BEN": ('Franklin Resources', "Financial Services", 'Asset Management & Custody Banks'),
    "BF-B": ('Brown–Forman', "Consumer Defensive", 'Distillers & Vintners'),
    "BG": ('Bunge Global', "Consumer Defensive", 'Agricultural Products & Services'),
    "BIIB": ('Biogen', "Healthcare", 'Biotechnology'),
    "BKNG": ('Booking Holdings', "Consumer Cyclical", 'Hotels, Resorts & Cruise Lines'),
    "BKR": ('Baker Hughes', "Energy", 'Oil & Gas Equipment & Services'),
    "BLK": ('BlackRock', "Financial Services", 'Asset Management & Custody Banks'),
    "BMY": ('Bristol Myers Squibb', "Healthcare", 'Pharmaceuticals'),
    "BNY": ('BNY Mellon', "Financial Services", 'Asset Management & Custody Banks'),
    "BR": ('Broadridge Financial Solutions', "Industrials", 'Data Processing & Outsourced Services'),
    "BRK-B": ('Berkshire Hathaway', "Financial Services", 'Multi-Sector Holdings'),
    "BRO": ('Brown & Brown', "Financial Services", 'Insurance Brokers'),
    "BSX": ('Boston Scientific', "Healthcare", 'Health Care Equipment'),
    "BX": ('Blackstone Inc.', "Financial Services", 'Asset Management & Custody Banks'),
    "BXP": ('BXP, Inc.', "Real Estate", 'Office REITs'),
    "C": ('Citigroup', "Financial Services", 'Diversified Banks'),
    "CAH": ('Cardinal Health', "Healthcare", 'Health Care Distributors'),
    "CARR": ('Carrier Global', "Industrials", 'Building Products'),
    "CASY": ("Casey's", "Consumer Defensive", 'Food Retail'),
    "CAT": ('Caterpillar Inc.', "Industrials", 'Construction Machinery & Heavy Transportation Equipment'),
    "CB": ('Chubb Limited', "Financial Services", 'Property & Casualty Insurance'),
    "CBOE": ('Cboe Global Markets', "Financial Services", 'Financial Exchanges & Data'),
    "CBRE": ('CBRE Group', "Real Estate", 'Real Estate Services'),
    "CCI": ('Crown Castle', "Real Estate", 'Telecom Tower REITs'),
    "CCL": ('Carnival Corporation', "Consumer Cyclical", 'Hotels, Resorts & Cruise Lines'),
    "CDNS": ('Cadence Design Systems', "Technology", 'Application Software'),
    "CDW": ('CDW Corporation', "Technology", 'Technology Distributors'),
    "CEG": ('Constellation Energy', "Utilities", 'Electric Utilities'),
    "CF": ('CF Industries', "Basic Materials", 'Fertilizers & Agricultural Chemicals'),
    "CFG": ('Citizens Financial Group', "Financial Services", 'Regional Banks'),
    "CHD": ('Church & Dwight', "Consumer Defensive", 'Household Products'),
    "CHRW": ('C.H. Robinson', "Industrials", 'Air Freight & Logistics'),
    "CHTR": ('Charter Communications', "Communication Services", 'Cable & Satellite'),
    "CI": ('Cigna', "Healthcare", 'Health Care Services'),
    "CIEN": ('Ciena', "Technology", 'Communications Equipment'),
    "CINF": ('Cincinnati Financial', "Financial Services", 'Property & Casualty Insurance'),
    "CL": ('Colgate-Palmolive', "Consumer Defensive", 'Household Products'),
    "CLX": ('Clorox', "Consumer Defensive", 'Household Products'),
    "CMCSA": ('Comcast', "Communication Services", 'Cable & Satellite'),
    "CME": ('CME Group', "Financial Services", 'Financial Exchanges & Data'),
    "CMG": ('Chipotle Mexican Grill', "Consumer Cyclical", 'Restaurants'),
    "CMI": ('Cummins', "Industrials", 'Construction Machinery & Heavy Transportation Equipment'),
    "CMS": ('CMS Energy', "Utilities", 'Multi-Utilities'),
    "CNC": ('Centene Corporation', "Healthcare", 'Managed Health Care'),
    "CNP": ('CenterPoint Energy', "Utilities", 'Multi-Utilities'),
    "COF": ('Capital One', "Financial Services", 'Consumer Finance'),
    "COHR": ('Coherent Corp.', "Technology", 'Electronic Components'),
    "COIN": ('Coinbase', "Financial Services", 'Financial Exchanges & Data'),
    "COO": ('Cooper Companies (The)', "Healthcare", 'Health Care Supplies'),
    "COP": ('ConocoPhillips', "Energy", 'Oil & Gas Exploration & Production'),
    "COR": ('Cencora', "Healthcare", 'Health Care Distributors'),
    "COST": ('Costco', "Consumer Defensive", 'Consumer Staples Merchandise Retail'),
    "CPAY": ('Corpay', "Financial Services", 'Transaction & Payment Processing Services'),
    "CPRT": ('Copart', "Industrials", 'Diversified Support Services'),
    "CPT": ('Camden Property Trust', "Real Estate", 'Multi-Family Residential REITs'),
    "CRH": ('CRH plc', "Basic Materials", 'Construction Materials'),
    "CRL": ('Charles River Laboratories', "Healthcare", 'Life Sciences Tools & Services'),
    "CRM": ('Salesforce', "Technology", 'Application Software'),
    "CRWD": ('CrowdStrike', "Technology", 'Systems Software'),
    "CSCO": ('Cisco', "Technology", 'Communications Equipment'),
    "CSGP": ('CoStar Group', "Real Estate", 'Real Estate Services'),
    "CSX": ('CSX Corporation', "Industrials", 'Rail Transportation'),
    "CTAS": ('Cintas', "Industrials", 'Diversified Support Services'),
    "CTSH": ('Cognizant', "Technology", 'IT Consulting & Other Services'),
    "CTVA": ('Corteva', "Basic Materials", 'Fertilizers & Agricultural Chemicals'),
    "CVNA": ('Carvana', "Consumer Cyclical", 'Automotive Retail'),
    "CVS": ('CVS Health', "Healthcare", 'Health Care Services'),
    "CVX": ('Chevron Corporation', "Energy", 'Integrated Oil & Gas'),
    "D": ('Dominion Energy', "Utilities", 'Multi-Utilities'),
    "DAL": ('Delta Air Lines', "Industrials", 'Passenger Airlines'),
    "DASH": ('DoorDash', "Consumer Cyclical", 'Specialized Consumer Services'),
    "DD": ('DuPont', "Industrials", 'Industrial Conglomerates'),
    "DDOG": ('Datadog', "Technology", 'Application Software'),
    "DE": ('Deere & Company', "Industrials", 'Agricultural & Farm Machinery'),
    "DECK": ('Deckers Brands', "Consumer Cyclical", 'Footwear'),
    "DELL": ('Dell Technologies', "Technology", 'Technology Hardware, Storage & Peripherals'),
    "DG": ('Dollar General', "Consumer Defensive", 'Consumer Staples Merchandise Retail'),
    "DGX": ('Quest Diagnostics', "Healthcare", 'Health Care Services'),
    "DHI": ('D. R. Horton', "Consumer Cyclical", 'Homebuilding'),
    "DHR": ('Danaher Corporation', "Healthcare", 'Life Sciences Tools & Services'),
    "DIS": ('Walt Disney Company (The)', "Communication Services", 'Movies & Entertainment'),
    "DLR": ('Digital Realty', "Real Estate", 'Data Center REITs'),
    "DLTR": ('Dollar Tree', "Consumer Defensive", 'Consumer Staples Merchandise Retail'),
    "DOC": ('Healthpeak Properties', "Real Estate", 'Health Care REITs'),
    "DOV": ('Dover Corporation', "Industrials", 'Industrial Machinery & Supplies & Components'),
    "DOW": ('Dow Inc.', "Basic Materials", 'Commodity Chemicals'),
    "DPZ": ("Domino's", "Consumer Cyclical", 'Restaurants'),
    "DRI": ('Darden Restaurants', "Consumer Cyclical", 'Restaurants'),
    "DTE": ('DTE Energy', "Utilities", 'Multi-Utilities'),
    "DUK": ('Duke Energy', "Utilities", 'Electric Utilities'),
    "DVA": ('DaVita', "Healthcare", 'Health Care Services'),
    "DVN": ('Devon Energy', "Energy", 'Oil & Gas Exploration & Production'),
    "DXCM": ('Dexcom', "Healthcare", 'Health Care Equipment'),
    "EBAY": ('eBay Inc.', "Consumer Cyclical", 'Broadline Retail'),
    "ECHO": ('EchoStar', "Communication Services", 'Wireless Telecommunication Services'),
    "ECL": ('Ecolab', "Basic Materials", 'Specialty Chemicals'),
    "ED": ('Consolidated Edison', "Utilities", 'Multi-Utilities'),
    "EFX": ('Equifax', "Industrials", 'Research & Consulting Services'),
    "EG": ('Everest Group', "Financial Services", 'Reinsurance'),
    "EIX": ('Edison International', "Utilities", 'Electric Utilities'),
    "EL": ('Estée Lauder Companies (The)', "Consumer Defensive", 'Personal Care Products'),
    "ELV": ('Elevance Health', "Healthcare", 'Managed Health Care'),
    "EME": ('Emcor', "Industrials", 'Construction & Engineering'),
    "EMR": ('Emerson Electric', "Industrials", 'Electrical Components & Equipment'),
    "EOG": ('EOG Resources', "Energy", 'Oil & Gas Exploration & Production'),
    "EQIX": ('Equinix', "Real Estate", 'Data Center REITs'),
    "EQT": ('EQT Corporation', "Energy", 'Oil & Gas Exploration & Production'),
    "ERIE": ('Erie Indemnity', "Financial Services", 'Insurance Brokers'),
    "ES": ('Eversource Energy', "Utilities", 'Electric Utilities'),
    "ESS": ('Essex Property Trust', "Real Estate", 'Multi-Family Residential REITs'),
    "ETN": ('Eaton Corporation', "Industrials", 'Electrical Components & Equipment'),
    "ETR": ('Entergy', "Utilities", 'Electric Utilities'),
    "EVRG": ('Evergy', "Utilities", 'Electric Utilities'),
    "EW": ('Edwards Lifesciences', "Healthcare", 'Health Care Equipment'),
    "EXC": ('Exelon', "Utilities", 'Electric Utilities'),
    "EXE": ('Expand Energy', "Energy", 'Oil & Gas Exploration & Production'),
    "EXPD": ('Expeditors International', "Industrials", 'Air Freight & Logistics'),
    "EXPE": ('Expedia Group', "Consumer Cyclical", 'Hotels, Resorts & Cruise Lines'),
    "EXR": ('Extra Space Storage', "Real Estate", 'Self-Storage REITs'),
    "F": ('Ford Motor Company', "Consumer Cyclical", 'Automobile Manufacturers'),
    "FANG": ('Diamondback Energy', "Energy", 'Oil & Gas Exploration & Production'),
    "FAST": ('Fastenal', "Industrials", 'Trading Companies & Distributors'),
    "FCX": ('Freeport-McMoRan', "Basic Materials", 'Copper'),
    "FDS": ('FactSet', "Financial Services", 'Financial Exchanges & Data'),
    "FDX": ('FedEx', "Industrials", 'Air Freight & Logistics'),
    "FDXF": ('FedEx Freight', "Industrials", 'Cargo Ground Transportation'),
    "FE": ('FirstEnergy', "Utilities", 'Electric Utilities'),
    "FERG": ('Ferguson Enterprises', "Industrials", 'Trading Companies & Distributors'),
    "FFIV": ('F5, Inc.', "Technology", 'Communications Equipment'),
    "FICO": ('Fair Isaac', "Technology", 'Application Software'),
    "FIS": ('Fidelity National Information Services', "Financial Services", 'Transaction & Payment Processing Services'),
    "FISV": ('Fiserv', "Financial Services", 'Transaction & Payment Processing Services'),
    "FITB": ('Fifth Third Bancorp', "Financial Services", 'Regional Banks'),
    "FIX": ('Comfort Systems USA', "Industrials", 'Construction & Engineering'),
    "FLEX": ('Flex Ltd.', "Technology", 'Electronic Manufacturing Services'),
    "FOX": ('Fox Corporation (Class B)', "Communication Services", 'Broadcasting'),
    "FOXA": ('Fox Corporation (Class A)', "Communication Services", 'Broadcasting'),
    "FRT": ('Federal Realty Investment Trust', "Real Estate", 'Retail REITs'),
    "FSLR": ('First Solar', "Technology", 'Semiconductors'),
    "FTNT": ('Fortinet', "Technology", 'Systems Software'),
    "FTV": ('Fortive', "Industrials", 'Industrial Machinery & Supplies & Components'),
    "GD": ('General Dynamics', "Industrials", 'Aerospace & Defense'),
    "GDDY": ('GoDaddy', "Technology", 'Internet Services & Infrastructure'),
    "GE": ('GE Aerospace', "Industrials", 'Aerospace & Defense'),
    "GEHC": ('GE HealthCare', "Healthcare", 'Health Care Equipment'),
    "GEN": ('Gen Digital', "Technology", 'Systems Software'),
    "GEV": ('GE Vernova', "Industrials", 'Heavy Electrical Equipment'),
    "GILD": ('Gilead Sciences', "Healthcare", 'Biotechnology'),
    "GIS": ('General Mills', "Consumer Defensive", 'Packaged Foods & Meats'),
    "GL": ('Globe Life', "Financial Services", 'Life & Health Insurance'),
    "GLW": ('Corning Inc.', "Technology", 'Electronic Components'),
    "GM": ('General Motors', "Consumer Cyclical", 'Automobile Manufacturers'),
    "GNRC": ('Generac', "Industrials", 'Heavy Electrical Equipment'),
    "GOOG": ('Alphabet Inc. (Class C)', "Communication Services", 'Interactive Media & Services'),
    "GOOGL": ('Alphabet Inc. (Class A)', "Communication Services", 'Interactive Media & Services'),
    "GPC": ('Genuine Parts Company', "Consumer Cyclical", 'Distributors'),
    "GPN": ('Global Payments', "Financial Services", 'Transaction & Payment Processing Services'),
    "GRMN": ('Garmin', "Consumer Cyclical", 'Consumer Electronics'),
    "GS": ('Goldman Sachs', "Financial Services", 'Investment Banking & Brokerage'),
    "GWW": ('W. W. Grainger', "Industrials", 'Industrial Machinery & Supplies & Components'),
    "HAL": ('Halliburton', "Energy", 'Oil & Gas Equipment & Services'),
    "HAS": ('Hasbro', "Consumer Cyclical", 'Leisure Products'),
    "HBAN": ('Huntington Bancshares', "Financial Services", 'Regional Banks'),
    "HCA": ('HCA Healthcare', "Healthcare", 'Health Care Facilities'),
    "HD": ('Home Depot (The)', "Consumer Cyclical", 'Home Improvement Retail'),
    "HIG": ('Hartford (The)', "Financial Services", 'Property & Casualty Insurance'),
    "HII": ('Huntington Ingalls Industries', "Industrials", 'Aerospace & Defense'),
    "HLT": ('Hilton Worldwide', "Consumer Cyclical", 'Hotels, Resorts & Cruise Lines'),
    "HON": ('Honeywell Technologies', "Industrials", 'Industrial Conglomerates'),
    "HONA": ('Honeywell Aerospace', "Industrials", 'Aerospace & Defense'),
    "HOOD": ('Robinhood Markets', "Financial Services", 'Investment Banking & Brokerage'),
    "HPE": ('Hewlett Packard Enterprise', "Technology", 'Technology Hardware, Storage & Peripherals'),
    "HPQ": ('HP Inc.', "Technology", 'Technology Hardware, Storage & Peripherals'),
    "HRL": ('Hormel Foods', "Consumer Defensive", 'Packaged Foods & Meats'),
    "HSIC": ('Henry Schein', "Healthcare", 'Health Care Distributors'),
    "HST": ('Host Hotels & Resorts', "Real Estate", 'Hotel & Resort REITs'),
    "HSY": ('Hershey Company (The)', "Consumer Defensive", 'Packaged Foods & Meats'),
    "HUBB": ('Hubbell Incorporated', "Industrials", 'Industrial Machinery & Supplies & Components'),
    "HUM": ('Humana', "Healthcare", 'Managed Health Care'),
    "HWM": ('Howmet Aerospace', "Industrials", 'Aerospace & Defense'),
    "IBKR": ('Interactive Brokers', "Financial Services", 'Investment Banking & Brokerage'),
    "IBM": ('IBM', "Technology", 'IT Consulting & Other Services'),
    "ICE": ('Intercontinental Exchange', "Financial Services", 'Financial Exchanges & Data'),
    "IDXX": ('Idexx Laboratories', "Healthcare", 'Health Care Equipment'),
    "IEX": ('IDEX Corporation', "Industrials", 'Industrial Machinery & Supplies & Components'),
    "IFF": ('International Flavors & Fragrances', "Basic Materials", 'Specialty Chemicals'),
    "ILMN": ('Illumina, Inc.', "Healthcare", 'Life Sciences Tools & Services'),
    "INCY": ('Incyte', "Healthcare", 'Biotechnology'),
    "INTC": ('Intel', "Technology", 'Semiconductors'),
    "INTU": ('Intuit', "Technology", 'Application Software'),
    "INVH": ('Invitation Homes', "Real Estate", 'Single-Family Residential REITs'),
    "IP": ('International Paper', "Basic Materials", 'Paper & Plastic Packaging Products & Materials'),
    "IQV": ('IQVIA', "Healthcare", 'Life Sciences Tools & Services'),
    "IR": ('Ingersoll Rand', "Industrials", 'Industrial Machinery & Supplies & Components'),
    "IRM": ('Iron Mountain', "Real Estate", 'Other Specialized REITs'),
    "ISRG": ('Intuitive Surgical', "Healthcare", 'Health Care Equipment'),
    "IT": ('Gartner', "Technology", 'IT Consulting & Other Services'),
    "ITW": ('Illinois Tool Works', "Industrials", 'Industrial Machinery & Supplies & Components'),
    "IVZ": ('Invesco', "Financial Services", 'Asset Management & Custody Banks'),
    "J": ('Jacobs Solutions', "Industrials", 'Construction & Engineering'),
    "JBHT": ('J.B. Hunt', "Industrials", 'Cargo Ground Transportation'),
    "JBL": ('Jabil', "Technology", 'Electronic Manufacturing Services'),
    "JCI": ('Johnson Controls', "Industrials", 'Building Products'),
    "JKHY": ('Jack Henry & Associates', "Financial Services", 'Transaction & Payment Processing Services'),
    "JNJ": ('Johnson & Johnson', "Healthcare", 'Pharmaceuticals'),
    "JPM": ('JPMorgan Chase', "Financial Services", 'Diversified Banks'),
    "KDP": ('Keurig Dr Pepper', "Consumer Defensive", 'Soft Drinks & Non-alcoholic Beverages'),
    "KEY": ('KeyCorp', "Financial Services", 'Regional Banks'),
    "KEYS": ('Keysight Technologies', "Technology", 'Electronic Equipment & Instruments'),
    "KHC": ('Kraft Heinz', "Consumer Defensive", 'Packaged Foods & Meats'),
    "KIM": ('Kimco Realty', "Real Estate", 'Retail REITs'),
    "KKR": ('KKR & Co.', "Financial Services", 'Asset Management & Custody Banks'),
    "KLAC": ('KLA Corporation', "Technology", 'Semiconductor Materials & Equipment'),
    "KMB": ('Kimberly-Clark', "Consumer Defensive", 'Household Products'),
    "KMI": ('Kinder Morgan', "Energy", 'Oil & Gas Storage & Transportation'),
    "KO": ('Coca-Cola Company (The)', "Consumer Defensive", 'Soft Drinks & Non-alcoholic Beverages'),
    "KR": ('Kroger', "Consumer Defensive", 'Food Retail'),
    "KVUE": ('Kenvue', "Consumer Defensive", 'Personal Care Products'),
    "L": ('Loews Corporation', "Financial Services", 'Multi-line Insurance'),
    "LDOS": ('Leidos', "Industrials", 'Diversified Support Services'),
    "LEN": ('Lennar', "Consumer Cyclical", 'Homebuilding'),
    "LH": ('Labcorp', "Healthcare", 'Health Care Services'),
    "LHX": ('L3Harris', "Industrials", 'Aerospace & Defense'),
    "LII": ('Lennox International', "Industrials", 'Building Products'),
    "LIN": ('Linde plc', "Basic Materials", 'Industrial Gases'),
    "LITE": ('Lumentum', "Technology", 'Communications Equipment'),
    "LLY": ('Lilly (Eli)', "Healthcare", 'Pharmaceuticals'),
    "LMT": ('Lockheed Martin', "Industrials", 'Aerospace & Defense'),
    "LNT": ('Alliant Energy', "Utilities", 'Electric Utilities'),
    "LOW": ("Lowe's", "Consumer Cyclical", 'Home Improvement Retail'),
    "LRCX": ('Lam Research', "Technology", 'Semiconductor Materials & Equipment'),
    "LULU": ('Lululemon Athletica', "Consumer Cyclical", 'Apparel, Accessories & Luxury Goods'),
    "LUV": ('Southwest Airlines', "Industrials", 'Passenger Airlines'),
    "LVS": ('Las Vegas Sands', "Consumer Cyclical", 'Casinos & Gaming'),
    "LYB": ('LyondellBasell', "Basic Materials", 'Specialty Chemicals'),
    "LYV": ('Live Nation Entertainment', "Communication Services", 'Movies & Entertainment'),
    "MA": ('Mastercard', "Financial Services", 'Transaction & Payment Processing Services'),
    "MAA": ('Mid-America Apartment Communities', "Real Estate", 'Multi-Family Residential REITs'),
    "MAR": ('Marriott International', "Consumer Cyclical", 'Hotels, Resorts & Cruise Lines'),
    "MAS": ('Masco', "Industrials", 'Building Products'),
    "MCD": ("McDonald's", "Consumer Cyclical", 'Restaurants'),
    "MCHP": ('Microchip Technology', "Technology", 'Semiconductors'),
    "MCK": ('McKesson Corporation', "Healthcare", 'Health Care Distributors'),
    "MCO": ("Moody's Corporation", "Financial Services", 'Financial Exchanges & Data'),
    "MDLZ": ('Mondelez International', "Consumer Defensive", 'Packaged Foods & Meats'),
    "MDT": ('Medtronic', "Healthcare", 'Health Care Equipment'),
    "MET": ('MetLife', "Financial Services", 'Life & Health Insurance'),
    "META": ('Meta Platforms', "Communication Services", 'Interactive Media & Services'),
    "MGM": ('MGM Resorts', "Consumer Cyclical", 'Casinos & Gaming'),
    "MKC": ('McCormick & Company', "Consumer Defensive", 'Packaged Foods & Meats'),
    "MLM": ('Martin Marietta Materials', "Basic Materials", 'Construction Materials'),
    "MMM": ('3M', "Industrials", 'Industrial Conglomerates'),
    "MNST": ('Monster Beverage', "Consumer Defensive", 'Soft Drinks & Non-alcoholic Beverages'),
    "MO": ('Altria', "Consumer Defensive", 'Tobacco'),
    "MOS": ('Mosaic Company (The)', "Basic Materials", 'Fertilizers & Agricultural Chemicals'),
    "MPC": ('Marathon Petroleum', "Energy", 'Oil & Gas Refining & Marketing'),
    "MPWR": ('Monolithic Power Systems', "Technology", 'Semiconductors'),
    "MRK": ('Merck & Co.', "Healthcare", 'Pharmaceuticals'),
    "MRNA": ('Moderna', "Healthcare", 'Biotechnology'),
    "MRSH": ('Marsh McLennan', "Financial Services", 'Insurance Brokers'),
    "MRVL": ('Marvell Technology', "Technology", 'Semiconductors'),
    "MS": ('Morgan Stanley', "Financial Services", 'Investment Banking & Brokerage'),
    "MSCI": ('MSCI', "Financial Services", 'Financial Exchanges & Data'),
    "MSFT": ('Microsoft', "Technology", 'Systems Software'),
    "MSI": ('Motorola Solutions', "Technology", 'Communications Equipment'),
    "MTB": ('M&T Bank', "Financial Services", 'Regional Banks'),
    "MTD": ('Mettler Toledo', "Healthcare", 'Life Sciences Tools & Services'),
    "MU": ('Micron Technology', "Technology", 'Semiconductors'),
    "NCLH": ('Norwegian Cruise Line Holdings', "Consumer Cyclical", 'Hotels, Resorts & Cruise Lines'),
    "NDAQ": ('Nasdaq, Inc.', "Financial Services", 'Financial Exchanges & Data'),
    "NDSN": ('Nordson Corporation', "Industrials", 'Industrial Machinery & Supplies & Components'),
    "NEE": ('NextEra Energy', "Utilities", 'Multi-Utilities'),
    "NEM": ('Newmont', "Basic Materials", 'Gold'),
    "NFLX": ('Netflix', "Communication Services", 'Movies & Entertainment'),
    "NI": ('NiSource', "Utilities", 'Multi-Utilities'),
    "NKE": ('Nike, Inc.', "Consumer Cyclical", 'Apparel, Accessories & Luxury Goods'),
    "NOC": ('Northrop Grumman', "Industrials", 'Aerospace & Defense'),
    "NOW": ('ServiceNow', "Technology", 'Systems Software'),
    "NRG": ('NRG Energy', "Utilities", 'Independent Power Producers & Energy Traders'),
    "NSC": ('Norfolk Southern', "Industrials", 'Rail Transportation'),
    "NTAP": ('NetApp', "Technology", 'Technology Hardware, Storage & Peripherals'),
    "NTRS": ('Northern Trust', "Financial Services", 'Asset Management & Custody Banks'),
    "NUE": ('Nucor', "Basic Materials", 'Steel'),
    "NVDA": ('Nvidia', "Technology", 'Semiconductors'),
    "NVR": ('NVR, Inc.', "Consumer Cyclical", 'Homebuilding'),
    "NWS": ('News Corp (Class B)', "Communication Services", 'Publishing'),
    "NWSA": ('News Corp (Class A)', "Communication Services", 'Publishing'),
    "NXPI": ('NXP Semiconductors', "Technology", 'Semiconductors'),
    "O": ('Realty Income', "Real Estate", 'Retail REITs'),
    "ODFL": ('Old Dominion', "Industrials", 'Cargo Ground Transportation'),
    "OKE": ('Oneok', "Energy", 'Oil & Gas Storage & Transportation'),
    "OMC": ('Omnicom Group', "Communication Services", 'Advertising'),
    "ON": ('ON Semiconductor', "Technology", 'Semiconductors'),
    "ORCL": ('Oracle Corporation', "Technology", 'Application Software'),
    "ORLY": ("O'Reilly Automotive", "Consumer Cyclical", 'Automotive Retail'),
    "OTIS": ('Otis Worldwide', "Industrials", 'Industrial Machinery & Supplies & Components'),
    "OXY": ('Occidental Petroleum', "Energy", 'Oil & Gas Exploration & Production'),
    "P": ('Everpure', "Technology", 'Technology Hardware, Storage & Peripherals'),
    "PANW": ('Palo Alto Networks', "Technology", 'Systems Software'),
    "PAYX": ('Paychex', "Industrials", 'Human Resource & Employment Services'),
    "PCAR": ('Paccar', "Industrials", 'Construction Machinery & Heavy Transportation Equipment'),
    "PCG": ('PG&E Corporation', "Utilities", 'Multi-Utilities'),
    "PEG": ('Public Service Enterprise Group', "Utilities", 'Electric Utilities'),
    "PEP": ('PepsiCo', "Consumer Defensive", 'Soft Drinks & Non-alcoholic Beverages'),
    "PFE": ('Pfizer', "Healthcare", 'Pharmaceuticals'),
    "PFG": ('Principal Financial Group', "Financial Services", 'Life & Health Insurance'),
    "PG": ('Procter & Gamble', "Consumer Defensive", 'Personal Care Products'),
    "PGR": ('Progressive Corporation', "Financial Services", 'Property & Casualty Insurance'),
    "PH": ('Parker Hannifin', "Industrials", 'Industrial Machinery & Supplies & Components'),
    "PHM": ('PulteGroup', "Consumer Cyclical", 'Homebuilding'),
    "PKG": ('Packaging Corporation of America', "Basic Materials", 'Paper & Plastic Packaging Products & Materials'),
    "PLD": ('Prologis', "Real Estate", 'Industrial REITs'),
    "PLTR": ('Palantir Technologies', "Technology", 'Application Software'),
    "PM": ('Philip Morris International', "Consumer Defensive", 'Tobacco'),
    "PNC": ('PNC Financial Services', "Financial Services", 'Diversified Banks'),
    "PNR": ('Pentair', "Industrials", 'Industrial Machinery & Supplies & Components'),
    "PNW": ('Pinnacle West Capital', "Utilities", 'Multi-Utilities'),
    "PODD": ('Insulet Corporation', "Healthcare", 'Health Care Equipment'),
    "PPG": ('PPG Industries', "Basic Materials", 'Specialty Chemicals'),
    "PPL": ('PPL Corporation', "Utilities", 'Electric Utilities'),
    "PRU": ('Prudential Financial', "Financial Services", 'Life & Health Insurance'),
    "PSA": ('Public Storage', "Real Estate", 'Self-Storage REITs'),
    "PSKY": ('Paramount Skydance Corporation', "Communication Services", 'Movies & Entertainment'),
    "PSX": ('Phillips 66', "Energy", 'Oil & Gas Refining & Marketing'),
    "PTC": ('PTC Inc.', "Technology", 'Application Software'),
    "PWR": ('Quanta Services', "Industrials", 'Construction & Engineering'),
    "PYPL": ('PayPal', "Financial Services", 'Transaction & Payment Processing Services'),
    "Q": ('Qnity Electronics', "Technology", 'Semiconductor Materials & Equipment'),
    "QCOM": ('Qualcomm', "Technology", 'Semiconductors'),
    "RCL": ('Royal Caribbean Group', "Consumer Cyclical", 'Hotels, Resorts & Cruise Lines'),
    "RDDT": ('Reddit', "Communication Services", 'Interactive Media & Services'),
    "REG": ('Regency Centers', "Real Estate", 'Retail REITs'),
    "REGN": ('Regeneron Pharmaceuticals', "Healthcare", 'Biotechnology'),
    "RF": ('Regions Financial Corporation', "Financial Services", 'Regional Banks'),
    "RJF": ('Raymond James Financial', "Financial Services", 'Investment Banking & Brokerage'),
    "RL": ('Ralph Lauren Corporation', "Consumer Cyclical", 'Apparel, Accessories & Luxury Goods'),
    "RMD": ('ResMed|', "Healthcare", 'Health Care Equipment'),
    "ROK": ('Rockwell Automation', "Industrials", 'Electrical Components & Equipment'),
    "ROL": ('Rollins, Inc.', "Industrials", 'Environmental & Facilities Services'),
    "ROP": ('Roper Technologies', "Technology", 'Electronic Equipment & Instruments'),
    "ROST": ('Ross Stores', "Consumer Cyclical", 'Apparel Retail'),
    "RSG": ('Republic Services', "Industrials", 'Environmental & Facilities Services'),
    "RTX": ('RTX Corporation', "Industrials", 'Aerospace & Defense'),
    "RVTY": ('Revvity', "Healthcare", 'Health Care Equipment'),
    "SBAC": ('SBA Communications', "Real Estate", 'Telecom Tower REITs'),
    "SBUX": ('Starbucks', "Consumer Cyclical", 'Restaurants'),
    "SCHW": ('Charles Schwab Corporation', "Financial Services", 'Investment Banking & Brokerage'),
    "SHW": ('Sherwin-Williams', "Basic Materials", 'Specialty Chemicals'),
    "SJM": ('J.M. Smucker Company (The)', "Consumer Defensive", 'Packaged Foods & Meats'),
    "SLB": ('Schlumberger', "Energy", 'Oil & Gas Equipment & Services'),
    "SMCI": ('Supermicro', "Technology", 'Technology Hardware, Storage & Peripherals'),
    "SNA": ('Snap-on', "Industrials", 'Industrial Machinery & Supplies & Components'),
    "SNDK": ('Sandisk', "Technology", 'Technology Hardware, Storage & Peripherals'),
    "SNPS": ('Synopsys', "Technology", 'Application Software'),
    "SO": ('Southern Company', "Utilities", 'Electric Utilities'),
    "SOLV": ('Solventum', "Healthcare", 'Health Care Technology'),
    "SPG": ('Simon Property Group', "Real Estate", 'Retail REITs'),
    "SPGI": ('S&P Global', "Financial Services", 'Financial Exchanges & Data'),
    "SRE": ('Sempra', "Utilities", 'Multi-Utilities'),
    "STE": ('Steris', "Healthcare", 'Health Care Equipment'),
    "STLD": ('Steel Dynamics', "Basic Materials", 'Steel'),
    "STT": ('State Street Corporation', "Financial Services", 'Asset Management & Custody Banks'),
    "STX": ('Seagate Technology', "Technology", 'Technology Hardware, Storage & Peripherals'),
    "STZ": ('Constellation Brands', "Consumer Defensive", 'Distillers & Vintners'),
    "SW": ('Smurfit Westrock', "Basic Materials", 'Paper & Plastic Packaging Products & Materials'),
    "SWK": ('Stanley Black & Decker', "Industrials", 'Industrial Machinery & Supplies & Components'),
    "SWKS": ('Skyworks Solutions', "Technology", 'Semiconductors'),
    "SYF": ('Synchrony Financial', "Financial Services", 'Consumer Finance'),
    "SYK": ('Stryker Corporation', "Healthcare", 'Health Care Equipment'),
    "SYY": ('Sysco', "Consumer Defensive", 'Food Distributors'),
    "T": ('AT&T', "Communication Services", 'Integrated Telecommunication Services'),
    "TDG": ('TransDigm Group', "Industrials", 'Aerospace & Defense'),
    "TDY": ('Teledyne Technologies', "Technology", 'Electronic Equipment & Instruments'),
    "TECH": ('Bio-Techne', "Healthcare", 'Life Sciences Tools & Services'),
    "TEL": ('TE Connectivity', "Technology", 'Electronic Manufacturing Services'),
    "TER": ('Teradyne', "Technology", 'Semiconductor Materials & Equipment'),
    "TFC": ('Truist Financial', "Financial Services", 'Diversified Banks'),
    "TGT": ('Target Corporation', "Consumer Defensive", 'Consumer Staples Merchandise Retail'),
    "TJX": ('TJX Companies', "Consumer Cyclical", 'Apparel Retail'),
    "TKO": ('TKO Group Holdings', "Communication Services", 'Movies & Entertainment'),
    "TMO": ('Thermo Fisher Scientific', "Healthcare", 'Life Sciences Tools & Services'),
    "TMUS": ('T-Mobile US', "Communication Services", 'Wireless Telecommunication Services'),
    "TPL": ('Texas Pacific Land Corporation', "Energy", 'Oil & Gas Exploration & Production'),
    "TPR": ('Tapestry, Inc.', "Consumer Cyclical", 'Apparel, Accessories & Luxury Goods'),
    "TRGP": ('Targa Resources', "Energy", 'Oil & Gas Storage & Transportation'),
    "TRMB": ('Trimble Inc.', "Technology", 'Application Software'),
    "TROW": ('T. Rowe Price', "Financial Services", 'Asset Management & Custody Banks'),
    "TRV": ('Travelers Companies (The)', "Financial Services", 'Property & Casualty Insurance'),
    "TSCO": ('Tractor Supply', "Consumer Cyclical", 'Other Specialty Retail'),
    "TSLA": ('Tesla, Inc.', "Consumer Cyclical", 'Automobile Manufacturers'),
    "TSN": ('Tyson Foods', "Consumer Defensive", 'Packaged Foods & Meats'),
    "TT": ('Trane Technologies', "Industrials", 'Building Products'),
    "TTWO": ('Take-Two Interactive', "Communication Services", 'Interactive Home Entertainment'),
    "TXN": ('Texas Instruments', "Technology", 'Semiconductors'),
    "TXT": ('Textron', "Industrials", 'Aerospace & Defense'),
    "TYL": ('Tyler Technologies', "Technology", 'Application Software'),
    "UAL": ('United Airlines Holdings', "Industrials", 'Passenger Airlines'),
    "UBER": ('Uber', "Industrials", 'Passenger Ground Transportation'),
    "UDR": ('UDR, Inc.', "Real Estate", 'Multi-Family Residential REITs'),
    "UHS": ('Universal Health Services', "Healthcare", 'Health Care Facilities'),
    "ULTA": ('Ulta Beauty', "Consumer Cyclical", 'Other Specialty Retail'),
    "UNH": ('UnitedHealth Group', "Healthcare", 'Managed Health Care'),
    "UNP": ('Union Pacific Corporation', "Industrials", 'Rail Transportation'),
    "UPS": ('United Parcel Service', "Industrials", 'Air Freight & Logistics'),
    "URI": ('United Rentals', "Industrials", 'Trading Companies & Distributors'),
    "USB": ('U.S. Bancorp', "Financial Services", 'Diversified Banks'),
    "V": ('Visa Inc.', "Financial Services", 'Transaction & Payment Processing Services'),
    "VEEV": ('Veeva Systems', "Healthcare", 'Health Care Technology'),
    "VICI": ('Vici Properties', "Real Estate", 'Hotel & Resort REITs'),
    "VLO": ('Valero Energy', "Energy", 'Oil & Gas Refining & Marketing'),
    "VLTO": ('Veralto', "Industrials", 'Environmental & Facilities Services'),
    "VMC": ('Vulcan Materials Company', "Basic Materials", 'Construction Materials'),
    "VMRK": ('Vivmark Residential', "Real Estate", 'Multi-Family Residential REITs'),
    "VRSK": ('Verisk Analytics', "Industrials", 'Research & Consulting Services'),
    "VRSN": ('Verisign', "Technology", 'Internet Services & Infrastructure'),
    "VRT": ('Vertiv', "Industrials", 'Electrical Components & Equipment'),
    "VRTX": ('Vertex Pharmaceuticals', "Healthcare", 'Biotechnology'),
    "VST": ('Vistra Corp.', "Utilities", 'Electric Utilities'),
    "VTR": ('Ventas', "Real Estate", 'Health Care REITs'),
    "VTRS": ('Viatris', "Healthcare", 'Pharmaceuticals'),
    "VZ": ('Verizon', "Communication Services", 'Integrated Telecommunication Services'),
    "WAB": ('Wabtec', "Industrials", 'Construction Machinery & Heavy Transportation Equipment'),
    "WAT": ('Waters Corporation', "Healthcare", 'Life Sciences Tools & Services'),
    "WBD": ('Warner Bros. Discovery', "Communication Services", 'Broadcasting'),
    "WDAY": ('Workday, Inc.', "Technology", 'Application Software'),
    "WDC": ('Western Digital', "Technology", 'Technology Hardware, Storage & Peripherals'),
    "WEC": ('WEC Energy Group', "Utilities", 'Electric Utilities'),
    "WELL": ('Welltower', "Real Estate", 'Health Care REITs'),
    "WFC": ('Wells Fargo', "Financial Services", 'Diversified Banks'),
    "WM": ('Waste Management', "Industrials", 'Environmental & Facilities Services'),
    "WMB": ('Williams Companies', "Energy", 'Oil & Gas Storage & Transportation'),
    "WMT": ('Walmart', "Consumer Defensive", 'Consumer Staples Merchandise Retail'),
    "WRB": ('W. R. Berkley Corporation', "Financial Services", 'Property & Casualty Insurance'),
    "WSM": ('Williams-Sonoma, Inc.', "Consumer Cyclical", 'Homefurnishing Retail'),
    "WST": ('West Pharmaceutical Services', "Healthcare", 'Health Care Supplies'),
    "WTW": ('Willis Towers Watson', "Financial Services", 'Insurance Brokers'),
    "WY": ('Weyerhaeuser', "Real Estate", 'Timber REITs'),
    "WYNN": ('Wynn Resorts', "Consumer Cyclical", 'Casinos & Gaming'),
    "XEL": ('Xcel Energy', "Utilities", 'Multi-Utilities'),
    "XOM": ('ExxonMobil', "Energy", 'Integrated Oil & Gas'),
    "XYL": ('Xylem Inc.', "Industrials", 'Industrial Machinery & Supplies & Components'),
    "XYZ": ('Block, Inc.', "Financial Services", 'Transaction & Payment Processing Services'),
    "YUM": ('Yum! Brands', "Consumer Cyclical", 'Restaurants'),
    "ZBH": ('Zimmer Biomet', "Healthcare", 'Health Care Equipment'),
    "ZBRA": ('Zebra Technologies', "Technology", 'Electronic Equipment & Instruments'),
    "ZTS": ('Zoetis', "Healthcare", 'Pharmaceuticals'),
}

DOW30 = ["AAPL", "AMGN", "AMZN", "AXP", "BA", "CAT", "CRM", "CSCO", "CVX", "DIS", "GS", "HD", "HON", "IBM", "JNJ", "JPM", "KO", "MCD",
         "MMM", "MRK", "MSFT", "NKE", "NVDA", "PG", "SHW", "TRV", "UNH", "V", "VZ", "WMT"]

GICS_AR = {
    "Advertising": "الإعلان", "Aerospace & Defense": "الطيران والدفاع", "Agricultural & Farm Machinery": "الآلات الزراعية",
    "Agricultural Products & Services": "المنتجات والخدمات الزراعية", "Air Freight & Logistics": "الشحن الجوي والخدمات اللوجستية",
    "Apparel Retail": "تجزئة الملابس", "Apparel, Accessories & Luxury Goods": "الملابس والإكسسوارات والسلع الفاخرة",
    "Application Software": "البرمجيات التطبيقية", "Asset Management & Custody Banks": "إدارة الأصول وبنوك الحفظ",
    "Automobile Manufacturers": "صناعة السيارات", "Automotive Parts & Equipment": "قطع ومعدات السيارات", "Automotive Retail": "تجزئة السيارات",
    "Biotechnology": "التقنية الحيوية", "Broadcasting": "البث الإذاعي والتلفزيوني", "Broadline Retail": "التجزئة الشاملة",
    "Building Products": "منتجات البناء", "Cable & Satellite": "الكابل والأقمار الصناعية", "Cargo Ground Transportation": "النقل البري للبضائع",
    "Casinos & Gaming": "الكازينوهات والألعاب", "Commodity Chemicals": "الكيماويات الأساسية", "Communications Equipment": "معدات الاتصالات",
    "Computer & Electronics Retail": "تجزئة الحواسيب والإلكترونيات", "Construction & Engineering": "الإنشاءات والهندسة",
    "Construction Machinery & Heavy Transportation Equipment": "معدات البناء والنقل الثقيل", "Construction Materials": "مواد البناء",
    "Consumer Electronics": "الإلكترونيات الاستهلاكية", "Consumer Finance": "التمويل الاستهلاكي",
    "Consumer Staples Merchandise Retail": "تجزئة السلع الأساسية", "Copper": "النحاس", "Data Center REITs": "صناديق مراكز البيانات",
    "Data Processing & Outsourced Services": "معالجة البيانات والخدمات الخارجية", "Distillers & Vintners": "المشروبات المقطرة",
    "Distributors": "الموزعون", "Diversified Banks": "البنوك المتنوعة", "Diversified Support Services": "خدمات الدعم المتنوعة",
    "Electric Utilities": "مرافق الكهرباء", "Electrical Components & Equipment": "المكونات والمعدات الكهربائية",
    "Electronic Components": "المكونات الإلكترونية", "Electronic Equipment & Instruments": "المعدات والأجهزة الإلكترونية",
    "Electronic Manufacturing Services": "خدمات التصنيع الإلكتروني", "Environmental & Facilities Services": "الخدمات البيئية والمرافق",
    "Fertilizers & Agricultural Chemicals": "الأسمدة والكيماويات الزراعية", "Financial Exchanges & Data": "البورصات والبيانات المالية",
    "Food Distributors": "موزعو الأغذية", "Food Retail": "تجزئة الأغذية", "Footwear": "الأحذية", "Gas Utilities": "مرافق الغاز", "Gold": "الذهب",
    "Health Care Distributors": "موزعو الرعاية الصحية", "Health Care Equipment": "المعدات الطبية", "Health Care Facilities": "المنشآت الصحية",
    "Health Care REITs": "صناديق العقارات الصحية", "Health Care Services": "الخدمات الصحية", "Health Care Supplies": "المستلزمات الطبية",
    "Health Care Technology": "تقنية الرعاية الصحية", "Heavy Electrical Equipment": "المعدات الكهربائية الثقيلة",
    "Home Improvement Retail": "تجزئة تحسين المنازل", "Homebuilding": "بناء المنازل", "Homefurnishing Retail": "تجزئة المفروشات",
    "Hotel & Resort REITs": "صناديق الفنادق والمنتجعات", "Hotels, Resorts & Cruise Lines": "الفنادق والمنتجعات والرحلات البحرية",
    "Household Products": "المنتجات المنزلية", "Human Resource & Employment Services": "خدمات الموارد البشرية والتوظيف",
    "IT Consulting & Other Services": "استشارات تقنية المعلومات", "Independent Power Producers & Energy Traders": "منتجو وتجار الطاقة المستقلون",
    "Industrial Conglomerates": "التكتلات الصناعية", "Industrial Gases": "الغازات الصناعية",
    "Industrial Machinery & Supplies & Components": "الآلات والمكونات الصناعية", "Industrial REITs": "صناديق العقارات الصناعية",
    "Insurance Brokers": "وسطاء التأمين", "Integrated Oil & Gas": "النفط والغاز المتكاملة", "Integrated Telecommunication Services": "الاتصالات المتكاملة",
    "Interactive Home Entertainment": "الترفيه المنزلي التفاعلي", "Interactive Media & Services": "الإعلام والخدمات التفاعلية",
    "Internet Services & Infrastructure": "خدمات وبنية الإنترنت", "Investment Banking & Brokerage": "البنوك الاستثمارية والوساطة",
    "Leisure Products": "المنتجات الترفيهية", "Life & Health Insurance": "التأمين على الحياة والصحة",
    "Life Sciences Tools & Services": "أدوات وخدمات علوم الحياة", "Managed Health Care": "الرعاية الصحية المُدارة",
    "Metal, Glass & Plastic Containers": "العبوات المعدنية والزجاجية والبلاستيكية", "Movies & Entertainment": "الأفلام والترفيه",
    "Multi-Family Residential REITs": "صناديق الشقق السكنية", "Multi-Sector Holdings": "الشركات القابضة المتنوعة", "Multi-Utilities": "المرافق المتعددة",
    "Multi-line Insurance": "التأمين متعدد الفروع", "Office REITs": "صناديق المكاتب", "Oil & Gas Equipment & Services": "معدات وخدمات النفط والغاز",
    "Oil & Gas Exploration & Production": "استكشاف وإنتاج النفط والغاز", "Oil & Gas Refining & Marketing": "تكرير وتسويق النفط والغاز",
    "Oil & Gas Storage & Transportation": "تخزين ونقل النفط والغاز", "Other Specialized REITs": "صناديق عقارية متخصصة",
    "Other Specialty Retail": "تجزئة متخصصة", "Packaged Foods & Meats": "الأغذية واللحوم المعلبة",
    "Paper & Plastic Packaging Products & Materials": "مواد التغليف الورقية والبلاستيكية", "Passenger Airlines": "شركات الطيران",
    "Passenger Ground Transportation": "النقل البري للركاب", "Personal Care Products": "منتجات العناية الشخصية", "Pharmaceuticals": "الأدوية",
    "Property & Casualty Insurance": "تأمين الممتلكات والحوادث", "Publishing": "النشر", "Rail Transportation": "السكك الحديدية",
    "Real Estate Services": "الخدمات العقارية", "Regional Banks": "البنوك الإقليمية", "Reinsurance": "إعادة التأمين",
    "Research & Consulting Services": "الأبحاث والاستشارات", "Restaurants": "المطاعم", "Retail REITs": "صناديق عقارات التجزئة",
    "Self-Storage REITs": "صناديق التخزين الذاتي", "Semiconductor Materials & Equipment": "معدات ومواد أشباه الموصلات",
    "Semiconductors": "أشباه الموصلات", "Single-Family Residential REITs": "صناديق المنازل السكنية",
    "Soft Drinks & Non-alcoholic Beverages": "المشروبات الغازية وغير الكحولية", "Specialized Consumer Services": "الخدمات الاستهلاكية المتخصصة",
    "Specialty Chemicals": "الكيماويات المتخصصة", "Steel": "الصلب", "Systems Software": "برمجيات الأنظمة", "Technology Distributors": "موزعو التقنية",
    "Technology Hardware, Storage & Peripherals": "الأجهزة التقنية والتخزين", "Telecom Tower REITs": "صناديق أبراج الاتصالات",
    "Timber REITs": "صناديق الأخشاب", "Tobacco": "التبغ", "Trading Companies & Distributors": "الشركات التجارية والموزعون",
    "Transaction & Payment Processing Services": "خدمات المدفوعات", "Water Utilities": "مرافق المياه",
    "Wireless Telecommunication Services": "الاتصالات اللاسلكية",
}


def gics_name(sub):
    return L(sub, GICS_AR.get(sub, sub)) if sub else "—"

# version stamp: app.py reloads any module still in memory from an older version of the site
BUILD = "7.9"
